# Generated by Django 3.1.2 on 2020-11-26 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201126_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dicount',
            new_name='discount',
        ),
    ]
