# Generated by Django 3.1.2 on 2020-11-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201128_1134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sub_Category',
            new_name='SubCategory',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='sub_category',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sub_category',
            new_name='subcategory',
        ),
    ]
